blank_issues_enabled: false
contact_links:
  - name: Tidaluna Discord
    url: https://discord.gg/yxZWK5AeZw
    about: If you need help regarding Radiant Lyrics or patches for Radiant Lyrics, please join the discord and make a post in the help forum.
